### PR TITLE
Revert "assignment-1 (resubmission).sh"

### PR DESCRIPTION
**Pull request by rktakk**
Reverts rktakk/shell#2

### CODE REVIEW

**Comment by rktakk** [comment]
@dtxe Hi Simeon, tagging you for homework review. Thank you.

**Comment by dwz92** [comment]
I can only see Question 1 being answered on my end.

**Comment by rktakk** [comment]
> I can only see Question 1 being answered on my end.

Hi Emma - I had accidentally merged my submission. I will try to re-upload after the class if that is ok. @dwz92

**Comment by dwz92** [comment]
> > I can only see Question 1 being answered on my end.
> 
> Hi Emma - I had accidentally merged my submission. I will try to re-upload after the class if that is ok. @dwz92

no prob

**Pull request closed without merging**
